# Generated by Django 6.1.1 on 2026-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={},
        ),
        migrations.AlterField(
            model_name="card",
            name="card_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="card",
            name="expiry_month",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="card",
            name="expiry_year",
            field=models.PositiveIntegerField(),
        ),
    ]
